### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by denzle83** [stereolabs/zed-open-capture#11]
Hi,
Could you give clearer details of the install process as the ones supplied are a little confusing. Particularly as it states to add the udev rule prior to cloning the open-capture folders. Does it need to be installed in which udev dir - lib, etc, run?

Thanks

**Comment by Myzhar** [comment]
Thank you for reporting the error in the Readme file.
Indeed the script to install the udev rules must be executed after cloning, not before.
I just fixed it.
