### ISSUE TITLE
Original ZED Cam (v1) Support?

### ISSUE THREAD

**Issue by Anebo** [stereolabs/zed-open-capture#16]
Hi, In the Prerequisites section of a project is mentioned ZED Cam in the list of possible devices. Once i've build the library and tried to run example it say that no ZED2 or ZED mini cam is connected. So my question is: Is the original ZED Cam (V1) supported or is it not? Thank You :)

**Comment by Myzhar** [comment]
For the ZED (1) camera you must disable the SensorCapture module because it's not equipped with inertial sensors. Set the following option to OFF:
https://github.com/stereolabs/zed-open-capture/blob/master/CMakeLists.txt#L31

**Comment by Anebo** [comment]
Thanks!
