### ISSUE TITLE
[Question] Cannot open camera video capture See verbosity level for more details.

### ISSUE THREAD

**Issue by LilyGinger** [stereolabs/zed-open-capture#19]
Seems that the device is not recognized in Ubuntu18.04 and no serial seems to be the one of the ZED. (NUCi711). Is there some reasons that may cause this problem? Thanks a lot.

**Comment by Myzhar** [comment]
Hi @jjjmmmxxx 
can you copy and paste the result of the `$ lsusb` command when the camera is connected?

**Comment by jjjmmmxxx** [comment]
Thanks a lot. Things have been fixed. Something goes wrong with the USB cable. It is not the problem of the camera or this API. Thank u~

**Comment by jjjmmmxxx** [comment]
Sorry to bother. It seems that I meet another problem. The examples except for the "zed_open_capture_sensors_example" and "zed_open_capture_sync_example" work well. But these two examples failed to run.
![screen](https://user-images.githubusercontent.com/44052488/130789975-5d2a2452-c27d-41c1-b047-14e1c4b4ee5f.png)

**Comment by Myzhar** [comment]
Can you post the result of the `$ lsusb` command?

**Comment by Myzhar** [comment]
Please also verify to have followed correctly the following installation steps:
https://github.com/stereolabs/zed-open-capture#add-udev-rule

If `udev` rules are not correctly installed the sensors module cannot be accessed without `sudo` rights

**Comment by jjjmmmxxx** [comment]
This is the lsusb output:
![test2](https://user-images.githubusercontent.com/44052488/130796209-83a0c431-f62f-4cb5-86f4-b4e9cfff1d03.png)

I tried this process again and I found it's still like that: No available ZED Mini or ZED2 cameras

![test3](https://user-images.githubusercontent.com/44052488/130796978-c47afdaf-88c6-4bfe-bd05-bfa6d1dd0b28.png)

![test4](https://user-images.githubusercontent.com/44052488/130797007-7edb4e80-1066-4f06-862a-6d302218a9b8.png)

**Comment by jjjmmmxxx** [comment]
It does seem something goes wrong when I follow the process for udev rules. When I add sudo before zed_open_capture_sensors_example, everything goes right.
![5](https://user-images.githubusercontent.com/44052488/130798472-8817d622-ca89-42c7-a227-efa7210ec93b.png)

**Comment by Myzhar** [comment]
Yes, that's because the ZED2i support was still missing in the udev rules. 
I fixed it only 2 hours ago when I noticed it, you can pull the new version (v0.4.1) from Github that should fix the problem.
I'm really sorry for this annoying bug.

**Comment by Myzhar** [comment]
Yes, it should work without any problems

**Comment by purpledeer111** [comment]
Hi,
    same message when using ZED mini with debian 11.

```
$ zed_open_capture_video_example 
Cannot open camera video capture
See verbosity level for more details.
```

Device seems to be recognized in system
```
$ lsusb 
...
Bus 001 Device 014: ID 2b03:f681 STEREOLABS ZED-M HID Interface
...
```

How do I increase verbosity level? I dont see any parameters
```
    if( !cap.initializeVideo() )
    {
        std::cerr << "Cannot open camera video capture" << std::endl;
        std::cerr << "See verbosity level for more details." << std::endl;

        return EXIT_FAILURE;
    }
```

**Comment by BhavyanshM** [comment]
I have been getting the exact same error with ZED2 on Ubuntu 20.04. Followed all the instructions as mentioned on the README. The C++ node runs and generates data. However, after a while the node freezes and doesn't get any more data from the cameras. 

Subsequent attempts at launching the node generate this message, and the node never starts. Only a complete computer reboot fixes it, which is a bit annoying because the freezes very regularly. Please help. Thank you so much. 
![image](https://user-images.githubusercontent.com/15614868/143394232-3979bd3d-f5e0-471d-9367-60a6e5b47cf1.png)

**Comment by Yelloooowww** [comment]
I have the same issue and reboot couldn't help.
![Screenshot from 2022-04-07 14-53-55](https://user-images.githubusercontent.com/37938491/162140599-de4fc519-675e-4cf6-83cf-735c50701aa0.png)

**Comment by Myzhar** [comment]
@Yelloooowww I'm sorry, but the reboot command only works starting from the ZED2 camera model.
The ZED-M does not have the electronic circuit for this behavior.

**Comment by ernlavr** [comment]
I have the same problem as described by a few people above! I've followed the README, running Ubuntu 22.04
![image](https://github.com/stereolabs/zed-open-capture/assets/40242518/f768ef5a-70af-4099-bc82-edd449b4db98)

**Comment by Myzhar** [comment]
@ernlavr this is a closed issue. Please do not reply to closed issues.
Create a new one with all the required information and eventually tag this issue as a reference.
