### ISSUE TITLE
Positional Tracking feature on CPU only

### ISSUE THREAD

**Issue by sumitsarkar1** [stereolabs/zed-open-capture#32]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, bug report, or anything other than a feature request directly related to this project.

### Proposal

Presently the [Positional Tracking](https://github.com/stereolabs/zed-examples/tree/master/positional%20tracking) works only on GPU with CUDA.  Kindly request to make available basic odometry/SLAM tracking with ZED cameras on CPU only. 

### Use-Case

Presently all ZED cameras are locked to NVIDIA boards which is not desiarable for UAVs and other Autonomous Vehicles having CPU only computes on board. WIth Intel T265 going EOL it will be really really helpful if simple tracking functionalities are made available on CPU only computes.

**Comment by Myzhar** [comment]
Hi @sumitsarkar1 
I'm sorry, but this is not planned.
