### ISSUE TITLE
Sensor_example working but Fails to run the video_example on zed2i 

### ISSUE THREAD

**Issue by Mandarhk** [stereolabs/zed-open-capture#38]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

I am using Zed2i over Linux 22.04 over VM(VM workstation pro)
After the successful build of all the examples and the library 
I can only able to run sensor_example and produces the sensor data.
but it fails to produce and gives output 
"Cannot open camera video capture" 
"See verbosity level for more details"

### Steps to Reproduce

1.Build the package 
2. try to run video_example
3.
...

### Expected Result

I want to run the video example and later also need to get the data in the ros2 humble . Thank You!

### Actual Result

![Untitled picture](https://github.com/stereolabs/zed-open-capture/assets/90417296/de963120-7518-4c70-b185-4da59b2ad012)
![Untitled picture3](https://github.com/stereolabs/zed-open-capture/assets/90417296/e3159e91-1445-45de-a3af-e282fb9ce494)
![Untitled picture2](https://github.com/stereolabs/zed-open-capture/assets/90417296/7b7f49c9-64b2-464d-b2d1-1293dcb67c14)

### ZED Camera model

ZED2i

### Environment

```shell
OS: Linux 22.04 (Over VM)
CPU: x86-64
GPU: No GPU(Cannot access through VM)
ZED SDK: Using open capture
```

**Comment by Myzhar** [comment]
Hi @Mandarhk 
can you open the camera with a webcam application like `cheese` or `guvcview`?
Can you copy and paste the output of the command `$ ls /dev/video*`?
Did you enable USB3 in your VM?

**Comment by Mandarhk** [comment]
Thank you for your prompt reply!
I tested with guvcview and /dev/video was not found 
later I tried changing USB3 setting in my VM but it was still not working.

But it finally worked in another VM with Linux 20. Is there any package support for the ROS2 wrapper

**Comment by Myzhar** [comment]
I'm sorry but we do not provide a ROS 2 Wrapper for the Open Capture driver, only for the full ZED SDK.

**Comment by Mandarhk** [comment]
Thank you for your help!
