### ISSUE TITLE
Cannot open camera video capture for examples

### ISSUE THREAD

**Issue by ernlavr** [stereolabs/zed-open-capture#39]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

Followed the README instructions and compiled the examples, when I try to run the examples I get the following error message

![image](https://github.com/stereolabs/zed-open-capture/assets/40242518/646194e8-a63d-4004-b169-7ca0be00871f)

### Steps to Reproduce

1. Run the examples

### Expected Result

1. Running the examples

### Actual Result

1. I've installed the udev rules
2. I've recompiled the example with `VGA` resolution 
![image](https://github.com/stereolabs/zed-open-capture/assets/40242518/89ffbbc9-b0ba-4e66-9733-a06ee349d0e7)

Here's my `lsusb` output
![image](https://github.com/stereolabs/zed-open-capture/assets/40242518/110a3697-060f-4f1f-bff4-2bffb597d186)

And here's my `lsusb -d 2b03: -v -t` output
![image](https://github.com/stereolabs/zed-open-capture/assets/40242518/e0c259b1-573d-464c-9710-205463ae6714)

### ZED Camera model

ZED Mini

### Environment

```shell
OS: Ubuntu 22.04
ZED SDK: None, I'm running it from my laptop which doesn't have CUDA GPU
Other: Dell XPS 13 2021
```

### Anything else?
Related but not helpful https://github.com/stereolabs/zed-open-capture/issues/35

_No response_

**Comment by Myzhar** [comment]
The UVC module of the camera is not enumerated. Have you tried to flip the TypeC connector?
The TypeC port of the ZED Mini works only on one side.
