### ISSUE TITLE
zed_open_capture_depth_example not working 

### ISSUE THREAD

**Issue by Mandarhk** [stereolabs/zed-open-capture#40]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

I tried to run the zed_open_capture_depth_example. After the successful build of the libraries with example.
![Screenshot from 2024-03-11 23-41-13](https://github.com/stereolabs/zed-open-capture/assets/90417296/e3687c4b-38b4-4e8f-811f-9254543d6495)

It is running the zed_open_capture_depth_tune_stereo example with no problem

### Steps to Reproduce

1.Build the library
2.Try to run the depth_example
3.
...

### Expected Result

It should run the zed_open_capture_depth_example

### Actual Result

it gives out zed_open_capture_depth_example: command not found

### ZED Camera model

ZED2i

### Environment

```shell
OS:Linux 22.04 Desktop  
NO SDK
```

**Comment by Myzhar** [comment]
Hi @Mandarhk 
Pleasecrun it with
`./zed_open_capture_depth_example`
