### ISSUE TITLE
Audio from mics and video/audio over IP (from IP cameras) support additional feature unique proposal to make commercially as per the initiator creating tech. startup.

### ISSUE THREAD

**Issue by goodengineer** [stereolabs/zed-open-capture#7]
Good afternoon.

Who is interested to add (with/wo creation of dedicated task force - research group for the purpose) Audio from mics and video/audio over IP (from IP cameras) support to ZED framework?

How much effort and cost it will take?

Kind Regards,
Paul.

**Comment by Myzhar** [comment]
Hi @goodengineer 
this is not the right place to talk about this topic.
I suggest you post it on the [community forum](https://community.stereolabs.com/)
