### ISSUE TITLE
[Question] Gstreamer error for opening ZED camera as UVC 

### ISSUE THREAD

**Issue by kumarvarma1** [stereolabs/zed-open-capture#8]
I am using Zed2 and want to use it as a UVC camera.I can detect the zed camera in cheese and using gstreamer but while trying to access it using Opencv I am getting an error " GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1".It works fine on laptop but i am getting this error only on jetson Xavier and I have tested with different jetson devices

**Comment by Myzhar** [comment]
@kumarvarma1 please stop cross-posting your question. 
This is an open-source driver, you can look at its code to try to fix your problem with OpenCV if this works correctly on the Xavier.
